**TASK:** import numpy

In [1]:
import numpy as np

**TASK:** define vector 'x' with three coordinates

In [2]:
x = np.array([[1,2], [3,4], [5,6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

**TASK:** define (2 x 2) matrix 'A' 


In [4]:
A = np.array([[1,3], [4,9]])
A

array([[1, 3],
       [4, 9]])

**TASK:** define (2 x 2) matrix 'B'

In [5]:
B = np.array([[1,5], [3,7]])
B

array([[1, 5],
       [3, 7]])

**TASK:** check the type of 'x'

In [6]:
type(x)

numpy.ndarray

**TASK:** check the type of 'A'

In [7]:
type(A)

numpy.ndarray

**TASK:**  check the shape of 'x'


In [8]:
x.shape

(3, 2)

**TASK:** check the type of 'A'

In [9]:
type(A)

numpy.ndarray

**TASK:** 

In [10]:
"""
Define function 'have_same_shape' which checks if two arrays have same shape.

PARAMS:
    array_1 (numpy.ndarray) - first array
    array_2 (numpy.ndarray) - second array
RETURN:
    True - if arrays have same shape
    False - if arrays do not have same shape

Also print 'Arrays must have same shape!' when returning False
"""

"\nDefine function 'have_same_shape' which checks if two arrays have same shape.\n\nPARAMS:\n    array_1 (numpy.ndarray) - first array\n    array_2 (numpy.ndarray) - second array\nRETURN:\n    True - if arrays have same shape\n    False - if arrays do not have same shape\n\nAlso print 'Arrays must have same shape!' when returning False\n"

In [11]:
def have_same_shape(array_1, array_2):
    if (array_1.shape == array_2.shape):
        return True
    print("Arrays must have same shape!")
    return False

**TASK:** call the function 'have_same_shape' with matrix 'A' and vector 'x' as inputs

In [12]:
have_same_shape(A, x)

Arrays must have same shape!


False

**TASK:**  call the function 'have_same_shape' with matrix 'A' and matrix 'B' as inputs

In [13]:
have_same_shape(A, B)

True

**TASK:** 

In [14]:
"""
Define function 'matrix_addition' which perform matrix addition value by value.

PARAMS:
    A (numpy.ndarray) - first array
    B (numpy.ndarray) - second array
RETURN:
    C (numpy.ndarray) - new A+B array

In this task do not consider broadcasting.
Do not forget to check arrays shapes (you can use 'have_same_shape' function defined before)

"""


"\nDefine function 'matrix_addition' which perform matrix addition value by value.\n\nPARAMS:\n    A (numpy.ndarray) - first array\n    B (numpy.ndarray) - second array\nRETURN:\n    C (numpy.ndarray) - new A+B array\n\nIn this task do not consider broadcasting.\nDo not forget to check arrays shapes (you can use 'have_same_shape' function defined before)\n\n"

In [19]:
def matrix_addition(A, B):
    if not have_same_shape(A, B):
        return None
    C = np.zeros_like(A)
    for r in range(A.shape[0]):
        for c in range(A.shape[1]):
            C[r,c] = A[r,c] + B[r,c]
    return C

**TASK:** call the function 'matrix_addition' with matrix 'A' and matrix 'B' as inputs

In [20]:
matrix_addition(A,B)

array([[ 2,  8],
       [ 7, 16]])

**TASK:** 

In [21]:
"""
Define 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition

PARAMS:
   lst_of_arr (list) - list of numpy.ndarrays
RETURN:
    NEW_ARRAY (numpy.ndarray) - new array

Use 'matrix_addition' function defined before.
"""

"\nDefine 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition\n\nPARAMS:\n   lst_of_arr (list) - list of numpy.ndarrays\nRETURN:\n    NEW_ARRAY (numpy.ndarray) - new array\n\nUse 'matrix_addition' function defined before.\n"

In [22]:
def multiple_matrix_addition(lst_of_arr):
    NEW_ARRAY = np.zeros_like(lst_of_arr[0])
    for a in lst_of_arr:
        NEW_ARRAY = matrix_addition(NEW_ARRAY, a)
    
    return NEW_ARRAY

**TASK:** call the function 'multiple_matrix_addition' with matrix [A,A,B,B,B] as input


In [23]:
multiple_matrix_addition([A,A,B,B,B])

array([[ 5, 21],
       [17, 39]])

**TASK:** 

In [24]:
"""
Define function 'can_multiply' that checks if two arrays (matrices) can be multiplied

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    True - if arrays can be multiplied, also print the shape of the new array
    False - if arrays can not be multiplied, also print 'Matrices can not be multiplied.'
    
"""

"\nDefine function 'can_multiply' that checks if two arrays (matrices) can be multiplied\n\nPARAMS:\n   array_a (numpy.ndarray) - first array\n   array_b (numpy.ndarray) - second array\nRETURN:\n    True - if arrays can be multiplied, also print the shape of the new array\n    False - if arrays can not be multiplied, also print 'Matrices can not be multiplied.'\n    \n"

In [30]:
def can_multiply(array_a, array_b):
    if array_a.shape[1] == array_b.shape[0]:
        print(f"Shape of multiplied array: ({array_a.shape[0]},{array_b.shape[1]})")
        return True
    
    print("Matrices can not be multiplied.")
    return False

**TASK:** call the function 'can_multiply' with matrix 'A' and 'B' as inputs

In [31]:
can_multiply(A,B)

Shape of multiplied array: (2,2)


True

**TASK:**  define matrix (3 x 2) matrix C

In [32]:
C = np.array([[1,2], [3,4], [5,6]])
C

array([[1, 2],
       [3, 4],
       [5, 6]])

**TASK:**  call the function 'can_multiply' with matrix 'A' and 'C' as inputs

In [33]:
can_multiply(A,C)

Matrices can not be multiplied.


False

**TASK:**  call the function 'can_multiply' with matrix 'C' and 'A' as inputs (now C,A not A,C). Do you know why is the result different?

In [34]:
can_multiply(C,A)

Shape of multiplied array: (3,2)


True

**TASK:** 

In [35]:
"""
Define function 'matrix_multiplication' that multiply two numpy.ndarrays

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    NEW_ARRAY (numpy.ndarray) - new A * B array
    
Do not forget to check if two matrices can be multiplied.

"""

"\nDefine function 'matrix_multiplication' that multiply two numpy.ndarrays\n\nPARAMS:\n   array_a (numpy.ndarray) - first array\n   array_b (numpy.ndarray) - second array\nRETURN:\n    NEW_ARRAY (numpy.ndarray) - new A * B array\n    \nDo not forget to check if two matrices can be multiplied.\n\n"

In [39]:
def matrix_multiplication(array_a, array_b):
    if can_multiply(array_a, array_b):
        return np.dot(array_a, array_b)
    return None

**TASK:**  call the function 'matrix_multiplication' with matrix 'C' and 'B' 


In [40]:
matrix_multiplication(C, B)

Shape of multiplied array: (3,2)


array([[ 7, 19],
       [15, 43],
       [23, 67]])

**TASK:** call the function 'matrix_multiplication' with matrix 'A' and 'C' 

In [41]:
matrix_multiplication(A, C)

Matrices can not be multiplied.
