In [1]:
import numpy as np

In [3]:
# Create a vector
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [4]:
# Create a (3,2) matrix
A = np.array([[1,2], [3,4], [5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
print(type(x))
print(type(A))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [7]:
# Shape of vector/matrix
print(x.shape)
print(A.shape)

(4,)
(3, 2)


In [8]:
# Transpose
A_T = A.T
A_T

array([[1, 3, 5],
       [2, 4, 6]])

In [10]:
A.transpose()

array([[1, 3, 5],
       [2, 4, 6]])

In [11]:
A_T.shape

(2, 3)

In [12]:
B = np.array([[2,5], [7,4], [4,3]])
B

array([[2, 5],
       [7, 4],
       [4, 3]])

In [13]:
C = A + B
C

array([[ 3,  7],
       [10,  8],
       [ 9,  9]])

In [15]:
D = A + 1
D

array([[2, 3],
       [4, 5],
       [6, 7]])

In [16]:
# matrix multiplication = find the dot product of two matrices
A = np.array([[1,2], [3,4], [5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
B = np.array([[2], [4]])
B

array([[2],
       [4]])

In [18]:
C = np.dot(A, B)
C

array([[10],
       [22],
       [34]])

In [19]:
C.shape

(3, 1)

In [20]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
IA = I.dot(A)
IA

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [23]:
M = np.array([[1,2], [3,4]])
M

array([[1, 2],
       [3, 4]])

In [24]:
det_M = np.linalg.det(M)  # only works for square matrices
det_M

-2.0000000000000004

In [25]:
M = np.array([[1,2],[3,4],[5,6]])
det_M = np.linalg.det(M)
det_M

LinAlgError: Last 2 dimensions of the array must be square

In [26]:
A = np.array([[3, 0, 2], [2, 0, -2], [0, 1, 1]])
A

array([[ 3,  0,  2],
       [ 2,  0, -2],
       [ 0,  1,  1]])

In [27]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.2,  0.2,  0. ],
       [-0.2,  0.3,  1. ],
       [ 0.2, -0.3, -0. ]])

In [29]:
I = A_inv.dot(A)
I

array([[ 1.00000000e+00,  0.00000000e+00, -1.11022302e-16],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])