## Load the NumPy library

In [1]:
import numpy as np

## The Basics

In [11]:
a = np.array([1, 2, 3], dtype='int16')
print(a)

[1 2 3]


In [12]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [13]:
# Dimension
a.ndim

1

In [14]:
# Shape
b.shape

(2, 3)

In [15]:
# Type
a.dtype

dtype('int16')

In [19]:
# item size in byte: int16 = 2 bytes = 16 bits
a.itemsize 

2

In [21]:
b.itemsize # float is 8 bytes

8

## Accessing and changing specific elements, rows, columns, etc.

In [23]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [24]:
a.shape

(2, 7)

In [25]:
# Get a specific element [row, col]
a[1, 5]

13

In [26]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [27]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [29]:
# [start idx: end idx: step size]
a[0, 1:6:2]

array([2, 4, 6])

## Initializing arrays

In [30]:
# All 0s
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [31]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
# All 1s
np.ones((3,3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [33]:
# Any other numbers
np.full((2,2), 10)

array([[10, 10],
       [10, 10]])

In [34]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.21281752, 0.9223493 ],
       [0.32328077, 0.28996216],
       [0.49275477, 0.99160129],
       [0.83798912, 0.22621064]])

In [37]:
# Random integer values
np.random.randint(2, 7, size=(3,3))

array([[6, 5, 5],
       [5, 6, 2],
       [6, 3, 4]])

In [40]:
# Generate an identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])