# NumPy exercises

We are going to practice NumPy skills and basic syntax.

We put here also some examples that were not in the tutorial on purpose. Try to use google and offial NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [5]:
np.empty(shape=10)

array([nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

#### 3.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
a = np.empty(shape=10)
a[4] = 1
a

array([nan,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.])

#### 4.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [11]:
b = np.arange(10, 50)
b

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 5.  Reverse a vector (first element becomes last) (★☆☆)

In [12]:
c = np.flip(b)
c

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 6.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [13]:
d = np.arange(0, 9)
d.reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 7. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [14]:
e = np.array([1,2,0,0,4,0])
np.where(e != 0)

(array([0, 1, 4], dtype=int64),)

#### 8. Create a 3x3x3 array with random values (★☆☆)

In [16]:
np.random.rand(3,3,3)

array([[[0.57890788, 0.49138919, 0.81755347],
        [0.28854932, 0.58647003, 0.32865487],
        [0.81835137, 0.54373798, 0.68978807]],

       [[0.33633223, 0.47711408, 0.67128557],
        [0.11602148, 0.7677341 , 0.01072795],
        [0.26014814, 0.84660451, 0.17522336]],

       [[0.38482686, 0.81373411, 0.08309873],
        [0.6728927 , 0.83473422, 0.25537485],
        [0.34697129, 0.93968527, 0.40760358]]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [19]:
f = np.random.rand(10, 10)
print('Min: ', np.min(f))
print('Max: ', np.max(f))

Min:  0.014210487763625546
Max:  0.9859007455240146


#### 10. Create a random vector of size 30 and find the mean value (★☆☆)

In [21]:
g = np.random.rand(30)
np.mean(g)

0.39233042440606086

#### 11. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [24]:
h = np.ones((5,5))
z = np.zeros((3,3))
h[1:4, 1:4] = z
h

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 12. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [33]:
y = np.random.randint(100, size=(2,5)) # random existing array
print(y)
z = np.zeros(np.array(y.shape) + 2, dtype='int32')
print(z)
z[1:-1, 1:-1] = y
z

[[ 6 92 39 26 61]
 [34  8  3 17 67]]
[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  6, 92, 39, 26, 61,  0],
       [ 0, 34,  8,  3, 17, 67,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

#### 13. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [35]:
0 * np.nan

nan

In [36]:
np.nan == np.nan

False

In [37]:
np.inf > np.nan

False

In [38]:
np.nan - np.nan

nan

In [39]:
np.nan in set([np.nan])

True

In [40]:
0.3 == 3 *0.1

False

#### 14. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [46]:
j = np.zeros((5,5), dtype='int32')
j[1,0],j[2,1], j[3,2], j[4,3] = (1,2,3,4)
j

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 15. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

#### 16. Normalize a 5x5 random matrix (★☆☆)

#### 17. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 18. How to round away from zero a float array ? (★☆☆)

#### 19. Find common values between two arrays? (★☆☆)

#### 20. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 21. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 22. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 23. Create a random vector of size 10 and sort it (★★☆)

In [52]:
a = np.random.randint(100, size=10)
a.sort()
a

array([13, 17, 41, 44, 66, 66, 76, 77, 79, 81])

#### 24. Consider two random arrays A and B, check if they are equal (★★☆)

In [55]:
A = np.random.randint(10, size=3)
B = np.random.randint(10, size=3)
print('A: ', A)
print('B: ', B)
np.array_equal(A, B)

A:  [0 4 1]
B:  [7 7 5]


False

#### 25. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [63]:
r = np.random.randint(100, size=10)
print(r)
idx = np.where(r == np.amax(r))
print(idx)

r[idx] = 0
r

[70 81 44 42  9  5 25 84 55 52]
(array([7], dtype=int64),)


array([70, 81, 44, 42,  9,  5, 25,  0, 55, 52])

#### 26. Find the closest value to random element in a vector? (★★☆)

#### 27. Convert a float (32 bits) array into an integer (32 bits) in place?

In [64]:
a = np.array([1.0, 2.0, 3.0, 4.0, 5.0])
a.dtype

dtype('float64')

In [65]:
b = a.astype('int32')
print(b)
b.dtype

[1 2 3 4 5]


dtype('int32')

#### 28. Sort an array by the nth column? (★★☆)

#### 29. Find if a given 2D array has null (empty) columns? (★★☆)

#### 30. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 31. Swap two rows of an array? (★★★)

#### 32. How to negate a boolean value inside an array? (★★★)

#### 33. Find the most frequent value in an array?

#### 34. Get the n largest values of an array (★★★)

#### 35. Extract unique rows from a two dimensional array? (★★★)